[build]
  functions = "functions/"
  publish = "build/"
  command = "npm run build"

[[redirects]]
  from = "/token/*"
  to = "/.netlify/functions/get-token?identity=:identity&roomName=:roomName"
  query = {identity = ":identity", roomName = ":roomName"}
  status = 302
